### ISSUE TITLE
Parcel Tracking Adapter

### ISSUE THREAD

**Issue by nob0dy80** [ioBroker/AdapterRequests#216]
Hello,
i'm receiving a lot of parcels and i thought it would be a lot of fun to have states if a parcel will be received on the next day.
there are a lot of possibilities to build an adapter but i'm not a programmer.

there are a lot of tracking sites that can handle tons of providers.
ex: https://www.1tracking.net/de/overview (API-documentation)

i requested api access to 17track.net cause this one is a lot better.
One other good provider is http://parcelapp.net/api.pdf (API-Documentation)

are my thoughts in any way realizable?

**Comment by ikkerus** [comment]
Usually logistic services automatically detect if a new parcel is attached to your adress and sends you an email notification. So, if you want to have Parcels automatically added to your Visualization, you need to integrate all major shipping companies with their own APIs into one adapter. 

For Automatic detection there are two information needed:

1. The TrackingID of the parcel
2. Your home adress

Some Shipping Companies require your post code to be added in order to query for the parcel.

I think an approach could also be to integrate an AllInOne-API such as https://www.trackingmore.com/i-parcel-tracking-api-de.html and help users to create a flow using node-RED adding their mail adress into the flow checking automattically for DHL, UPS Tracking IDs. Just an idea...

**Comment by Grothesk242** [comment]
I would love to see an adapter a parcel prediction service like parcello.org 
With the data I would activate my Nuki Opener for the Parcel Delivery guys.

**Comment by jack-blackson** [comment]
I would give it a try to set up such an adapter. I am currently checking the trackingmore.com API, one other is the https://www.easypost.com one, which has no limits

**Comment by Keyronics** [comment]
https://status.api.dhl.com/
DHL seems to have API´s as well. Would be great to have an Adapter in ioBroker :)

**Comment by TA2k** [comment]
I create a adapter for dhl and 17track so far
https://forum.iobroker.net/topic/51795/test-adapter-parcel-paketverfolgung-dhl-v0-0-1

**Comment by ldittmar81** [comment]
https://github.com/TA2k/ioBroker.parcel
