### ISSUE TITLE
Velux KIX 300 Adapter

### ISSUE THREAD

**Issue by od1001** [ioBroker/AdapterRequests#244]
https://www.velux.de/produkte/smart-home/velux-active-raumklimasteuerung
Da steht zwar "VELUX ACTIVE with NETATMO"; aber mit Netatmo hat das System von Velux herzlich wenig zu tun, denn es gibt keine Verbindung zwischen den beiden Systemen.
Leider habe ich keine weiteren Informationen...

**Comment by od1001** [comment]
PortScan hat einen offenen Port gefunden: 5001

**Comment by TA2k** [comment]
Wenn jemand Zugangsdaten für die App bereitstellt kann ich ein Adapter schreiben.

**Comment by roelbroersma** [comment]
There is already a lot of information (including an 'CLI API') available:  https://github.com/nougad/velux-cli


Also see here for OpenHab binding: https://community.openhab.org/t/connecting-velux-active-kix-300/75696/12


Personally I am using KNX,  So I am following these developments,.. maybe I can create a KNX hook or fork somewhere... If you write something generic... otherwise I will just do it via ioBroker

**Comment by roelbroersma** [comment]
(Note,  we are talking about the  NEW  Velux Active system here,  also known as KIX300 gateway,... we are NOT talking for an API for KLR200)

**Comment by od1001** [comment]
I don't know what to do. I don't know the clientSecret and the clientId.

**Comment by TA2k** [comment]
Wie gesagt mit temporären Zugangsdaten könnte ich schnell ein Adapter bauen.

**Comment by roelbroersma** [comment]
What do you need ?   I have a gateway,  I also have a Velux account,,. i can reset my password...?

**Comment by TA2k** [comment]
Write me in the IoBroker forum my name is tombox

**Comment by TA2k** [comment]
https://forum.iobroker.net/user/tombox

**Comment by TA2k** [comment]
First version at the moment read only because I need a record of the gateway key authentication
https://forum.iobroker.net/topic/26400/test-adapter-velux-v0-0-x

**Comment by TA2k** [comment]
@od1001  Könntest du mir helfen Rolladen zu testen?

**Comment by TA2k** [comment]
ist in latest
