### ISSUE TITLE
mydlink Home Smart Plug DSP w215

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/AdapterRequests#25]
http://forum.iobroker.net/viewtopic.php?f=36&t=5181&p=53680#p53680

Here is a repository where a lot of work is done already, next step is use this code to build a Adapter.
https://github.com/bikerp/dsp-w215-hnap

Migrated from Trello with 2 votes

**Comment by Apollon77** [comment]
Homebridge modules exist: homebridge-w215 as example.

Please check if the new ioBroker.ham Adapter can help here: see https://forum.iobroker.net/viewtopic.php?f=36&t=14972

**Comment by Garfonso** [comment]
Hi,
I have a dsp w215 plug and wanted to look into creating an adapter, because it seems easy enough as a start for adapter development. 😃 
I'm currently wondering about the name a bit. My first intention was to go with "iobroker.mydlink", because the thread about the plug was the only hit in the forum for mydlink and I also have a motion detector which I might look into adding in the future.
But then I had a look at the dlink webpage and it seems that they also sell a lot of cameras under the label "mydlink". That could cause some confusion.

What would be your suggestion?

**Comment by Garfonso** [comment]
I think we can mark this as released (or whatever happens to theses requests). the mydlink adapter works quite well with dsp-w215 now and also with dch-s150 (motion detector).
There seem to be some issues with newer hardware, which I am investigating, but that should not require another adapter. :-)

**Comment by Apollon77** [comment]
Great, thank you!
