### ISSUE TITLE
Adapter for ESPHome

### ISSUE THREAD

**Issue by FredF63** [ioBroker/AdapterRequests#404]
ESPhome is widely used from homeassistant users worldwide possibly due to the native API which is used from homeassistant.
Having an ESPHome adapter could help the international distribution of ioBroker.
https://esphome.io/components/api.html

**Comment by klassisch** [comment]
There exist doku
https://esphome.io/components/api.html
https://esphome.io/api/api__server_8h.html
@Apollon77 What does it mean "Hardware needed"? Do you need an ESP8266 or an ESP32? I could prepare one and send it to you.

**Comment by Apollon77** [comment]
> @Apollon77 What does it mean "Hardware needed"?

In fact not me, but the developer that starts with this will needs something like this in general ...

**Comment by mgernhard** [comment]
ESP8266 or ESP32 costs less than 5€ 
From China less than 2$

I can gift hardware if needed.

An ESP integration would be awesome.
There are coming up some projects with esp for f.e. peoplecounter ...

**Comment by DutchmanNL** [comment]
Happy testing :)

https://github.com/iobroker-community-adapters/ioBroker.esphome

**Comment by DutchmanNL** [comment]
> An ESP integration would be awesome.
> There are coming up some projects with esp for f.e. peoplecounter ...

so I expect a lot of feedback from you :)

**Comment by klassisch** [comment]
I can try to give feedback:
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\iobroker\\ioBrMain026\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\iobroker\\ioBrMain026\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'https://github.com/iobroker-community-adapters/ioBroker.esphome/tarball/master',
1 verbose cli   '--loglevel',
1 verbose cli   'error' ]
2 info using npm@6.11.3
3 info using node@v10.17.0
4 verbose npm-session 8586a4b6efc791ff
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://codeload.github.com/iobroker-community-adapters/ioBroker.esphome/legacy.tar.gz/master 627ms
8 silly fetchPackageMetaData error for https://github.com/iobroker-community-adapters/ioBroker.esphome/tarball/master 404 Not Found - GET https://codeload.github.com/iobroker-community-adapters/ioBroker.esphome/legacy.tar.gz/master
9 timing stage:rollbackFailedOptional Completed in 2ms
10 timing stage:runTopLevelLifecycles Completed in 36303ms
11 verbose stack Error: 404 Not Found - GET https://codeload.github.com/iobroker-community-adapters/ioBroker.esphome/legacy.tar.gz/master
11 verbose stack     at res.buffer.catch.then.body (C:\Program Files\iobroker\ioBrMain026\nodejs\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:104:15)
11 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
12 verbose statusCode 404
13 verbose pkgid https://github.com/iobroker-community-adapters/ioBroker.esphome/tarball/master
14 verbose cwd C:\Program Files\iobroker\ioBrMain026
15 verbose Windows_NT 10.0.19042
16 verbose argv "C:\\Program Files\\iobroker\\ioBrMain026\\nodejs\\node.exe" "C:\\Program Files\\iobroker\\ioBrMain026\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/iobroker-community-adapters/ioBroker.esphome/tarball/master" "--loglevel" "error"
17 verbose node v10.17.0
18 verbose npm  v6.11.3
19 error code E404
20 error 404 Not Found - GET https://codeload.github.com/iobroker-community-adapters/ioBroker.esphome/legacy.tar.gz/master
21 error 404
22 error 404 'https://github.com/iobroker-community-adapters/ioBroker.esphome/tarball/master' is not in the npm registry.
23 error 404 Your package name is not valid, because
24 error 404 1. name can only contain URL-friendly characters
25 error 404 2. name can no longer contain capital letters
26 error 404 Note that you can also install from a
27 error 404 tarball, folder, http url, or git url.
28 verbose exit [ 1, true ]
`

**Comment by klassisch** [comment]
Thanks a lot! Now I updated my system to controller v3.2.6 and the installation of the adapter works.

**Comment by DutchmanNL** [comment]
Forum test-thread : https://forum.iobroker.net/topic/42741/esphome-beta-release?_=1614498596722
Dokumentation : https://dutchmannl.github.io/languages/en/ESPHome/

**Comment by quorle** [comment]
Würde die Integration klappen, damit man das ESPHome gleich aus ioBroker aus Programmieren und auf die ESP´s schreiben kann? Bei Home-Assistant klappt es ja wunderbar. Sollte doch mit ioBroker auch funktionieren?

Das wäre natürlich ein neuer und großer Fortschritt für ioBroker. Da man seine Sensoren und Aktoren, die mittels ESP laufen, gleich von einem System aus Programmieren kann. Änderungen, Anpassungen, Überwachung der Sensoren und Aktoren wäre alles von einem System aus möglich.

**Comment by DutchmanNL** [comment]
> Würde die Integration klappen, damit man das ESPHome gleich aus ioBroker aus Programmieren und auf die ESP´s schreiben kann? Bei Home-Assistant klappt es ja wunderbar. Sollte doch mit ioBroker auch funktionieren?

ja, macht die Installation installation aber unnötig komplex da ioBroker auf NodeJS basiert und ESPHome af python.
Ergo man mus python verstehen, installieren etc ich werd es mir anschauen ob man das integrieren kan brauch dabei aber Hilfe.

Bis dahin werde ich auf meiner docu Seite ein Docker setup verfassen als workarround
