### ISSUE TITLE
Bubendorff / Netatmo iDiamant rolling shutter controller

### ISSUE THREAD

**Issue by AtrejuAZ** [ioBroker/AdapterRequests#788]
**What kind of device or service you would like to see an adapter for?**
https://solar.bubendorff.com/de/fernbedienungen-und-haustechnik/idiamant-with-netatmo/
It's a controller for Bubendorff rolling shutters

**Is the device connected to the internet or only in the local network available?**
both, as far as I know

**Is an official App or Website available?**
https://apps.apple.com/au/app/home-control/id1188809809?l=de

**Is an official API including documentation available?**
https://dev.netatmo.com/apidocumentation/control

**Are other libraries for an integration available?**
https://github.com/clementprevot/home-assistant-idiamant
Maybe this one gives some hints

**Is this device already integrated in other Smart Home systems?**
I don't know

**Comment by mcm1957** [comment]
Did you check whther the netato adapter already supports this device?
If not, wouldn't a feature request for this adapter the next step before implementing another adapter?

**Comment by AtrejuAZ** [comment]
Hello mcm1857, 
Yes, I tried this adapter, but it only supports devices like weather stations or doorbells…

**Comment by mcm1957** [comment]
Thank for replyin to the first question.
Waht about the second?
>If not, wouldn't a feature request for this adapter the next step before implementing another adapter?
If you do no have any concerns that the mentioned adapter (https://github.com/PArns/ioBroker.netatmo/) can be extended to support this device the next step would be to create a feature request issue at the adapters repo or to contact the developer directly to check if an extension of the existing adapter seems to be possible.

A new adapter should be considered only if the existing one cannot support your device.

**Comment by Apollon77** [comment]
@AtrejuAZ Yes the adapter YET supports on lxy this because noone requested that Netatmo feature so far ... So I close here. Please open a new issue in the Githb of the Netatmo adapter. After you have done that please install and connect the adapter to your netatmo account. Then enable Debug log for the instance (Adapter - expertmode - netatmo.0 expand, change loglevel). The adapter then restarts. Please get this full log after restart from Logfile on disk (/opt/iobroker/log/...) and send it to me as email to iobroker@fischer-ka.de and add a reference to the created GitHub issue.

When i find time I will look into it
