### ISSUE TITLE
Redesigned Chromecast adapter

### ISSUE THREAD

**Issue by maxpd1** [ioBroker/AdapterRequests#791]
**What kind of device or service would you like to see an adapter for?**
Control Google Home Mini and other Chromecast devices. Especially make speeches

**Is the device connected to the internet or only available on a local network?**
both

**Is an official App or Website available?**
There is an adapter yet for it, which isn't working quite well and no developer available anymore.
https://github.com/iobroker-community-adapters/ioBroker.chromecast

**Is an official API including documentation available?**
I assume: https://developers.google.com/cast

**Addition**
The existing adapter shows the following problems:

- loudness is varying uncontrollable during speeches
- speeches are looped several times
- speech indication (*bing*) is made in time but speech itself has a delay up to 4 minutes.
- Connection timeouts
- several warnings and errors in logs
- sometimes changed values of a chromecast device aren't visible in iobroker adapter

**Comment by mcm1957** [comment]
@maxpd1 
A short look at https://github.com/iobroker-community-adapters/ioBroker.chromecast shows that the adapter seems to be maintained at all. A new release has been created 20 days ago (by GermanBlueFox)

So I suggest you add your problems / feature requests as issues at the adapter repository. Thats the correct place to register problems. If those issues are not processed or commented there, a request here might be useful.

@GermanBluefox 
As you worked at chromecast adapter some days ago - whats you oppinion? Is a look for a new maintainer really required?
Otherwise I suggest to close this issue here.

**Comment by Apollon77** [comment]
We close here. As a community adapter many developers can get access, so open issues about wishes there as freature request. It don not help to have a new adapter request
