### ISSUE TITLE
Daheimladen Wallbox

### ISSUE THREAD

**Issue by StevieC121176** [ioBroker/AdapterRequests#800]
**What kind of device or service would you like to see an adapter for?**
Wallbox Daheimladen. [www.daheimladen.de](url)

**Is the device connected to the internet or only available on a local network?**
connected to internet over Lan and Wlan

**Is an official App or Website available?**
https://www.daheimladen.de/post/modbus-api

**Is an official API including documentation available?**
https://www.daheimladen.de/post/modbus-api

**Is this device already integrated in other Smart Home systems?**
possible, node red, node js

**Comment by Apollon77** [comment]
Why not using modbus adapter if you refer to a "modbus api"?

**Comment by mcm1957** [comment]
@StevieC121176 
If I understand your cpomment correctly, modbus is not yet working due to problems with Daheimladen firmware.
And according to your request Daheimladen supports access via modbus only ( at least the linked documents seem to indicate that based on their names)

So please let us know when a firmware supporting modbus is available and working. And please indicate why a dedicated adapter should be considered if a modbus interface is available.

**Comment by StevieC121176** [comment]
Ich habe die Firmware nun installiert bekommen, damit funktioniert auch der Modus Adapter in ioBroker. Das gilt allerdings für die Daheimladen Touch, bei der Daheimladen smart kann ich es nicht sagen.

**Comment by mcm1957** [comment]
Thanks for the feedback.

**Comment by Stingray79** [comment]
@StevieC121176 : Kannst du mir einen Screenshot machen, wie du den modbus adapter im ioBroker eingestellt hast? Ich habe die Anleitung nicht ganz verstanden. Danke.

**Comment by StevieC121176** [comment]
Hier mal ein paar Screenshots. 

![Screenshot_20230128_190102_Samsung Internet](https://user-images.githubusercontent.com/113791299/215283498-67d2e1eb-07c9-4c67-9587-e9bb446da389.png)
![Screenshot_20230128_190231_Samsung Internet](https://user-images.githubusercontent.com/113791299/215283499-cfec17ff-ba6b-4778-a88f-55a7ae229f36.png)
![Screenshot_20230128_190244_Samsung Internet](https://user-images.githubusercontent.com/113791299/215283500-5ad82334-bdd8-4892-8811-2f7247a247b5.png)

**Comment by Stingray79** [comment]
![Screenshot 2023-01-29 125531](https://user-images.githubusercontent.com/45821783/215324459-07d547ac-ce72-4b3c-a1f1-bcd702b836c2.jpg)

**Comment by Stingray79** [comment]
Danke für die Screenshots
Was hast du denn bei Typ angegeben?

Ist ein State oder value?

**Comment by Stingray79** [comment]
Ich sehe gerade mein Hauptproblem ist die folgender Fehlermeldung: 
On error: {"errno":-113,"code":"EHOSTUNREACH","syscall":"connect","address":"192.168.188.93","port":502
Er kann sich nicht verbinden mit der Wallbox.

**Comment by StevieC121176** [comment]
![20230129_144350_resized](https://user-images.githubusercontent.com/113791299/215330268-35bd74af-8b4a-4750-b42a-33da7a468b17.jpg)

**Comment by StevieC121176** [comment]
richtige Firmware auf der Wallbox?

**Comment by Stingray79** [comment]
![Screenshot_2023-01-29-16-17-44-204-edit_com miui gallery](https://user-images.githubusercontent.com/45821783/215336162-87182173-92a6-4b36-b143-0999d3ae580c.jpg)

**Comment by Stingray79** [comment]
Das sollte die richtige sein.
Ich finde die Wallbox in meiner Fritzbox nicht wieder unter aktiven Verbindungen

**Comment by mcm1957** [comment]
Auf Grund der letzten Beiträge ist anzunehmen, dass MODBUS nun mit der aktuellen Firmware funktioniert. Ich erlaube mir den Request daher zu schließen.

Sollte jemand einen Grund sehen einen dedizierten Adapter zu implementieren, bitte hier melden - dann kann der Request jederzeit neu geöffnet werden.

-------------------------

The last comments indicate that MODBUS is now working wehn using the lates firmware. I will close this request because of this.

If you see any reason to implement a dedicated adapter please respond here. The request can be reopend at any time.

**Comment by mcm1957** [comment]
For support discussion please use the forum.
Please add working modbus templates here: https://github.com/ioBroker/modbus-templates

**Comment by Stingray79** [comment]
@StevieC121176 : Hallo, hast du es eingestellt bekommen, das du im ioBroker über Modbus die Ladung in der daheimladen.de wallbox stoppen?

**Comment by dj-mib** [comment]
> stoppen

Würde mich auch interessieren
