### ISSUE TITLE
Zendure SolarFlow Adapter

### ISSUE THREAD

**Issue by DeathForce07** [ioBroker/AdapterRequests#849]
**What kind of device or service would you like to see an adapter for?**
Zendure SolarFlow Speicher für Balkonkraftwerke

**Is the device connectsed to the internet or only available on a local network?**
Internetverbindung über WLAN

**Is an official App or Website available?**
Es gibt scheinbar bereits eine API

**Is an official API including documentation available?**
https://github.com/Zendure/developer-device-data-report

**Additional context**
Wäre Super wenn man die bereits angebotenen Datenpunkte auslesen könnte. :)

**Comment by nograx** [comment]
Ist von mir in Arbeit. Ich hoffe demnächst eine erste Version zur Verfügung stellen kann.

**Comment by mcm1957** [comment]
Thanks for spending your time to develop an ioBroker adapter,

Please feel free to ask for support whenever you feel the nedd for it.

I suggest to join out telegram goups (mirrored to discord too)

https://t.me/+gsX-e8k4mLtmZjZk - iobroker development starters (german)
https://t.me/ioBroker_development (german)
https://t.me/ioBroker_dev_en (english)

Please add some comment stating why you are atending after joining (i.e. 'Hi, I plan ti develop adpter xyz') to avoid to be kicked out as spam bot due to no reaction.

Feel free to ping me for assistance. If you wish, I can perform a quick scan over an adaptercode to check for obvious thinks to adapt befor listing an adapter to out repositories.

mcm1957

**Comment by nograx** [comment]
Hi,

the adapter is available as a alpha test via npm or github.

Npm: https://www.npmjs.com/package/iobroker.zendure-solarflow
Github: https://github.com/nograx/ioBroker.zendure-solarflow

if possible take some time to submit Feedback in the official ioBroker forum: https://forum.iobroker.net/topic/69579/test-adapter-zendure-solarflow/3?_=1698844263203

Kind regards,
Peter

**Comment by DutchmanNL** [comment]
> the adapter is available as a alpha test via npm or github.

looks good thank you ! Small advice: I would prefer to use extendObject instead of setObject not exist for object/state creations as that also allows you if things are changed to update the current objects.

SetObjectNotExist would only be executed once, if you change attributes people need to delete the adapter states

**Comment by nograx** [comment]
Thanks for Info, will change that!

**Comment by mcm1957** [comment]
Repo: https://github.com/nograx/ioBroker.zendure-solarflow

adapter has been released to lates repository.

Please create an issue at the adapter repository if you encounter a problem or want to suggest a new feature.
