### ISSUE TITLE
Askoheat+ Pover to Heat

### ISSUE THREAD

**Issue by sansonifabio** [ioBroker/AdapterRequests#896]
**What kind of device or service would you like to see an adapter for?**
https://www.askoma.com/de/produkte/produkte-fuer-den-pv-markt/askoheat.html#

**Is the device connected to the internet or only available on a local network?**
Local Network

**Is an official App or Website available?**
https://www.askoma.com/de/

**Is an official API including documentation available?**
https://www.askoma.com/fileadmin/produkte/Montageanleitungen/MV-012-6391.1.pdf
http://www.download.askoma.com/askofamily_plus/modbus/askoheat-modbus.html
http://www.download.askoma.com/askofamily_plus/modbus/askoheat-json.html

**Are other libraries for an integration available?**
http://www.download.askoma.com/askofamily_plus/modbus/askoheat-python.html

**Is this device already integrated in other Smart Home systems?**
https://www.askoma.com/de/produkte/produkte-fuer-den-pv-markt/askofamily.html

**Is this device already integrated in homebridge? Might the ham adapter in combination with the homebridge plugin be sufficient?**
No 

**Additional context**
It would be nice if the adapter reads the data and also controls the heating element at the same time. At the moment it works for me with the Modbus adapter, which is quite complex for me.

After you create the issue, please vote for yourself in the first post of the issue using the "+1"/"Thumbs up" button

**Comment by DutchmanNL** [comment]
Da das System über Modbus kommuniziert, währe im Grunde ein Adapter nicht notwendig das geht mit dem modbus adapter

Das schonmal probiert ?

Doku vom Hersteller : http://www.download.askoma.com/askofamily_plus/modbus/askoheat-modbus.html

Modbus Adapter: https://github.com/ioBroker/ioBroker.modbus

**Comment by mcm1957** [comment]
Looks like the device has a modbus interface:

> Die 7 Leistungsstufen werden über Modbus TCP/RTU, REST API JSON oder über 0-10V gesteuert.

**Comment by sansonifabio** [comment]
Additional context
It would be nice if the adapter reads the data and also controls the heating element at the same time. At **the moment it works for me with the Modbus adapter, which is quite complex for me.**

**Comment by DutchmanNL** [comment]
> Additional context It would be nice if the adapter reads the data and also controls the heating element at the same time. At **the moment it works for me with the Modbus adapter, which is quite complex for me.**

As modes is a wide protocol, is quite inefficient to build separate adapter for that puporse (as we agreed in Developer meeting).

I see 2 options to make this exercise easier, modbus adapter has the capability to use templates. Purpose is if someone has a device and implemented the register to also share it with the community.
I fully understand its not a perfect solution, but please also imagine that building a separate adapter for same protocol is a little overhead.

these templates can be found and share here : https://github.com/ioBroker/modbus-templates

Option 2, this protocol has also en HTTP API, but its data polling only. So its possible to build an easy API-Read adapter to handle this but also has negative sides:

- separate development based on HTTP request API instead of modbus communication
- Rest API is pull only, no push of data (so modbus is more efficient)
